Rex2002/sound-investments

src/main/java/app/mapping/InstrumentDataRaw.java, src/main/java/audio/harmonizer/Harmonizer.java, src/main/java/audio/synth/InstrumentData.java
- adds double validity checks as discussed in code review
- adds null-checks for all parameters that can be not mapped
- adds onOff parameter for filter, echo, reverb
=> feat(Harmonizer): add FX onOff and check whether params are mapped

src/main/resources/MainScene.fxml
Nach Ändernung der Globalen Parameter wieder anpassung, dass kein leerer Platz entsteht
=> fixed UI design

src/main/java/audio/Sonifier.java, src/main/java/audio/mixer/Mixer.java
=> fix(mixer): reduce volume of backing track

src/main/java/app/StateManager.java, src/main/java/audio/synth/EvInstrData.java, src/main/java/audio/synth/EvInstrEnum.java, src/main/java/audio/synth/EvInstrLine.java, src/main/java/dataAnalyzer/GeneralTrends.java, src/main/java/dataRepo/DataRepo.java
this should now work. 
Only problem is with the data-analysis, all but the movingAvg throw "Not yet implemented"-errors
=> 102 connect backing instruments

src/main/java/audio/harmonizer/Harmonizer.java
I think @ArtInLines idea described in the issue makes sense :+1:
=> feat: should resolve #118

src/main/java/app/StateManager.java, src/main/java/app/mapping/Mapping.java, src/main/java/app/ui/MusicSceneController.java, src/main/java/audio/harmonizer/Harmonizer.java, src/main/java/audio/mixer/Backing.java, src/main/java/audio/synth/playback/PlaybackController.java
merging this only makes sense if from now on all new AppErrors are written in german.
=> feat: translate AppErrors to german.

src/main/java/dataRepo/DataRepo.java
=> More api keys

src/main/java/app/ui/MusicSceneController.java
@nichtLehdev will you look at that - another miniscule change to fix the issue xD
=> resolve #135

.gitignore, DistReadme.txt, README.md, build.bash, build.bat, buildForManjaro.bash, pom.xml, src/main/java/audio/mixer/SampleLoader.java
Added build scripts to create the deliverable. We have boh a batch and a bash script this time, so linux/mac users should also be able to build the deliverable (though I couldn't properly test that on my windows machine of course).
Instructions on how to execute the build-process are in the README. Everybody feel free to test if it works on your machine (both the building and running the actual deliverable afterwards. You can also find the deliverable as I created it on my machine [here](https://github.com/Rex2002/sound-investments/releases/tag/test), so you can also just try out whether that works for you (regardless of wheteher you can build the project yourself)
=> Deliverable

src/main/java/app/StateManager.java, src/main/java/util/Maths.java
I now calculate the standard deviation before normalizing the price-values. If the standard deviation is below the magical number of 10, we linearly reduce the range available to the normalized values, making sure that they are always in te middle between 0 and 1 though (for example, normalized range turning to 0.35 to 0.65)
=> resolve #96

src/main/java/app/ui/MusicSceneController.java, src/main/java/util/DateUtil.java
Quick fix to show the Dates on the LineChart's X-Axis in german date-format
=> resolves #162

src/main/java/audio/harmonizer/Harmonizer.java
I was too slow to get this into the reverb-fix PR so this is a new one...
=> Remove commented out code in Harmonizer

src/main/java/app/mapping/PointData.java, src/main/java/dataAnalyzer/GeneralTrends.java, src/main/java/dataAnalyzer/TriangleFormationAnalyzer.java
=> fixed issue 170 - triangle formation

src/main/java/app/ui/CommonController.java, src/main/resources/UI/choice.css
ist nur btn besser machen kann weggemergt werden dann
=> btn look fix

src/main/java/app/ui/MainSceneController.java, src/main/java/dataRepo/DataRepo.java, src/main/java/dataRepo/Sonifiable.java
=> feat(UI): add symbol to display name

src/main/java/app/ui/App.java, src/main/java/app/ui/MainSceneController.java, src/main/java/app/ui/MusicSceneController.java
I simplified the code for changing UI scenes a little and probably improved performance too, as we don't load the same css again every time.
This was just a piece of code I was able to salvage from my hours wasted in making the UI resizable
=> simplified UI scene-change

src/main/java/audio/Sonifier.java, src/main/java/audio/harmonizer/Harmonizer.java, src/main/java/audio/mixer/Backing.java, src/main/java/audio/mixer/Mixer.java, src/main/java/audio/mixer/MixerException.java, src/main/java/audio/mixer/SampleLoader.java, src/main/java/audio/synth/EvInstrLine.java, src/main/java/audio/synth/SynthLine.java, src/main/java/audio/synth/envelopes/ADSR.java, src/main/java/audio/synth/fx/Effect.java, src/main/java/audio/synth/generators/SineWaveGenerator.java
PR for tracking audio technical documentation
=> chore: start adding docstrings

src/main/java/dhbw/si/app/ui/MainSceneController.java
Fixxed cretain iusses with instCB listener.
=> UI choices

src/main/java/dhbw/si/util/DateUtil.java
I had just forgotten to add +1 to the month, bc java starts counting months at 0 🤦
=> resolves #207

src/main/resources/UI/MainScene.fxml, src/main/resources/UI/choice.css
See the whole stockname by having a width-scrollbar
=> width scrollbar

src/main/java/dhbw/si/app/StateManager.java, src/main/java/dhbw/si/app/mapping/EvInstrMapping.java, src/main/java/dhbw/si/app/mapping/ExchangeData.java, src/main/java/dhbw/si/app/mapping/InstrumentMapping.java, src/main/java/dhbw/si/app/mapping/Mapping.java, src/main/java/dhbw/si/app/ui/MainSceneController.java, src/main/java/dhbw/si/app/ui/MusicSceneController.java, src/main/java/dhbw/si/audio/Sonifier.java, src/main/java/dhbw/si/audio/playback/PlayControlEvent.java, src/main/java/dhbw/si/dataRepo/API.java, src/main/java/dhbw/si/dataRepo/DataRepo.java, src/main/java/dhbw/si/dataRepo/IntervalLength.java, src/main/java/dhbw/si/dataRepo/Price.java, src/main/java/dhbw/si/dataRepo/Sonifiable.java, src/main/java/dhbw/si/dataRepo/SonifiableID.java, src/main/java/dhbw/si/dataRepo/api/APIReq.java, src/main/java/dhbw/si/dataRepo/api/ErrHandler.java, src/main/java/dhbw/si/dataRepo/json/JsonPrimitive.java, src/main/java/dhbw/si/util/FutureList.java, src/main/java/dhbw/si/util/UnorderedList.java, src/main/java/module-info.java
I removed outdated comments, unused imports and boilerplate that lombok can create instead. Also updated the module-info the way that my IDE advised me to, as it otherwise showed some warnings for some variables.
=> Minor cleanup

src/main/java/dhbw/si/dataAnalyzer/Analyzer.java
=> revert "fix" from a second ago

src/main/java/dhbw/si/audio/Harmonizer.java
reverb can now be heard more often (but is only really noticeable if one pays attention)
=> feat: increase max_reverb_delay

src/main/java/dhbw/si/dataRepo/DataRepo.java
=> MOOOOOOOOOREEEEEEEEE

src/main/java/dhbw/si/app/ui/MusicSceneController.java, src/main/resources/UI/MusicScene.fxml
=> UI back fix

src/main/java/dhbw/si/app/StateManager.java
The issue was that the list of prices was sometimes differently ordered than the list of names.... should be fixed now
=> resolve #228

src/main/java/dhbw/si/dataRepo/DataRepo.java
Writing the right variable name is hard... But now it works and searching for Healtineers also shows Siemens
=> resolves #242

src/main/java/dhbw/si/app/StateManager.java, src/main/java/dhbw/si/dataRepo/DataRepo.java
Can be tested with Aareal Bank AG ADR (AAALY) in the default time-range for example
=> resolves #231

src/main/java/dhbw/si/app/ui/MainSceneController.java, src/main/java/dhbw/si/util/DateUtil.java
feels ultra-hacky, but somehow works
=> fix: should fix #234 by overriding internal date validation

src/main/java/dhbw/si/app/ui/CommonController.java, src/main/java/dhbw/si/app/ui/MainSceneController.java, src/main/java/dhbw/si/app/ui/MusicSceneController.java, src/main/resources/UI/MainScene.fxml, src/main/resources/UI/MusicScene.fxml, src/main/resources/UI/choice.css
I decided to leave #204 as it is and instead focus on something that is far more important for tomorrow imo: Having a UI that fits on the screen.
If it works with the projector we can also use the originally sized UI, but in case it doesn, this should make the UI fit on a normal laptop screen
=> Smaller UI
